batchSize: 100

spring:
  application:
    name: kakaopay_server
  h2:
    console:
      enabled: true
      path: /h2-console
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/kakaopay?profileSQL=true&logger=Slf4JLogger&maxQuerySizeToLog=999999&rewriteBatchedStatements=true
#    username: root
#    password: mysql
  datasource:
    platform: h2
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: "jdbc:log4jdbc:h2:mem:kakaopay_server;MODE=MYSQL;DB_CLOSE_DELAY=-1;"
    username: sa
    password:
server:
  port: 8080
